# Audit policy mounted into the control-plane node.
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages: ["RequestReceived"]
rules:
  - level: None
    users: ["system:kube-proxy", "system:apiserver"]
    verbs: ["watch", "list", "get"]
  - level: None
    resources:
      - group: ""
        resources: ["events", "endpoints"]
      - group: "events.k8s.io"
        resources: ["events"]
      - group: "coordination.k8s.io"
        resources: ["leases"]
  - level: Metadata
    resources:
      - group: ""
        resources: ["secrets", "configmaps"]
      - group: "authentication.k8s.io"
  - level: RequestResponse
    resources:
      - group: "rbac.authorization.k8s.io"
  - level: Request
    verbs: ["create", "update", "patch", "delete", "deletecollection"]
  - level: Metadata
