# Second, smaller cluster for service-mesh work. Uses kind's default CNI.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mesh
nodes:
  - role: control-plane
    image: __IMAGE__
  - role: worker
    image: __IMAGE__
