#!/usr/bin/env python3
"""Generate assets/drill-data.js and assets/drill-index.js from the self-check panels.

Every <details class="quiz"> in a page's #selfcheck panel becomes one flashcard.

Two files, one pass. drill-data.js is the whole bank and only the drill needs it.
drill-index.js is the same cards without the prose, which is all the dashboard
counts by: a sixth of the bytes, a seventh gzipped.

    python3 tools/extract-drill.py            # rewrite both files
    python3 tools/extract-drill.py --check    # exit 1 if either is stale
"""
import glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "assets", "drill-data.js")
INDEX = os.path.join(ROOT, "assets", "drill-index.js")

QUIZ = re.compile(
    r'<details class="quiz"><summary>(.*?)</summary>\s*<div class="answer">(.*?)</div></details>',
    re.S)
SELFCHECK = re.compile(r'<section[^>]*id="selfcheck"[^>]*>(.*?)</section>', re.S)


def slug(s):
    text = re.sub(r"<[^>]+>", "", s)
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:48]


def tidy(html):
    return re.sub(r"\s+", " ", html).strip()


def extract():
    cards = []
    for path in sorted(glob.glob(os.path.join(ROOT, "0*", "*.html"))):
        src = open(path, encoding="utf-8").read()
        sec = re.search(r'data-id="([^"]+)"', src).group(1)
        panel = SELFCHECK.search(src)
        if not panel:
            sys.exit("no #selfcheck panel in " + path)
        blocks = QUIZ.findall(panel.group(1))
        opened = panel.group(1).count('<details class="quiz">')
        if len(blocks) != opened:
            sys.exit("%s: %d quiz blocks but only %d matched the expected shape"
                     % (path, opened, len(blocks)))
        seen = set()
        for q, a in blocks:
            qid = sec + "#" + slug(q)
            n = 2
            while qid in seen:
                qid = sec + "#" + slug(q) + "-" + str(n)
                n += 1
            seen.add(qid)
            cards.append({"id": qid, "sec": sec, "q": tidy(q), "a": tidy(a)})
    return cards


def render(cards):
    lines = [json.dumps(c, ensure_ascii=False).replace("</", "<\\/") for c in cards]
    return ("/* Generated by tools/extract-drill.py. "
            "Edit the section pages, then regenerate. */\n"
            "window.CNPE_DRILL = [\n" + ",\n".join(lines) + "\n];\n")


def render_index(cards):
    """The same deck with the prose cut away: id and section, nothing else."""
    lines = [json.dumps({"id": c["id"], "sec": c["sec"]}, ensure_ascii=False).replace("</", "<\\/")
             for c in cards]
    return ("/* Generated by tools/extract-drill.py. "
            "Edit the section pages, then regenerate. */\n"
            "/* The deck the dashboard counts by. The drill loads drill-data.js. */\n"
            "window.CNPE_DRILL_INDEX = [\n" + ",\n".join(lines) + "\n];\n")


cards = extract()
FILES = [(OUT, render(cards)), (INDEX, render_index(cards))]
if "--check" in sys.argv:
    for path, want in FILES:
        rel = os.path.relpath(path, ROOT)
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if current != want:
            sys.exit("%s is stale: run tools/extract-drill.py and commit the result" % rel)
    print("drill data in sync (%d questions)" % len(cards))
else:
    for path, text in FILES:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
    per = {}
    for c in cards:
        per[c["sec"]] = per.get(c["sec"], 0) + 1
    print("wrote %s and %s (%d questions from %d sections, %d-%d per section)"
          % (os.path.relpath(OUT, ROOT), os.path.relpath(INDEX, ROOT),
             len(cards), len(per), min(per.values()), max(per.values())))
