apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    gitea.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    # Wire these up once you enable the Argo CD / Kubernetes frontend plugins.
    argocd/app-name: ${{ values.name }}-dev
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=${{ values.name }}'
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
