# Backstage creates a repo; this ApplicationSet discovers it.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: golden-path
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - scmProvider:
        gitea:
          owner: services
          api: http://gitea.lab:3000/
          allBranches: false
          insecure: true
          tokenRef:
            secretName: gitea-token
            key: token
        cloneProtocol: https
        filters:
          - pathsExist: [k8s/overlays/dev]
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{ .repository }}-dev'
    spec:
      project: default
      source:
        repoURL: '{{ .url }}'
        targetRevision: '{{ .branch }}'
        path: k8s/overlays/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .repository }}-dev'
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]
