apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-b
namePrefix: prod-
resources: [../../base]
replicas:
  - { name: demo, count: 3 }
patches:
  - target: { kind: Deployment, name: demo }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
